name: 🐞 Bug report
description: Thanks for taking the time to fill out this bug report! Please fill the form in **English**
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is (if it's a keyboard issue, provide the keyboard mode you're using. e.g. legacy, map, translate)
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to Reproduce
      description: What steps can we take to reproduce this behavior?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system(s) on local side and remote side
      description: What operating system(s) do you see this bug on? local side -> remote side.
      placeholder: |
        Windows 10 -> osx
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: RustDesk Version(s) on local side and remote side
      description: What RustDesk version(s) do you see this bug on? local side -> remote side.
      placeholder: |
        1.1.9 -> 1.1.8
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots to help explain your problem, if applicable, please upload video.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additonal context about the problem here
